'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

fib = []
fibEve = []
a = 1 
b = 2
c = 0

length1 = 4000000

while c < length1:
    c = a+b
    fib.append(a)
    fib.append(b)
    b = b+c
    a = c

for i in fib:
    if i % 2 ==0:
        fibEve.append(i)
    
print(sum(fibEve))
